### ISSUE TITLE
v2 auth & permissions refactor

### ISSUE THREAD

**Issue by maxachis** [Police-Data-Accessibility-Project/data-sources-app#318]
Part of #248 
Follows #196 

### Context

This may be able to exist as a replacement for at least some of the current logic in `security.py`, and may be more extensible and easier to work with than custom code. However, I have not looked into this, and can't testify as to its utility. 

~~https://flask-httpauth.readthedocs.io/en/latest/~~
https://github.com/lepture/authlib

### Requirements

- [x] #383 
- [x] #162 
- [x] #296
- [x] #322 
- [x] #387 
- [x] #388
- [x] https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/491

We uncovered that each "role" for us is basically one "permission". These are the things people can do:

permission/role | note
--- | ---
db write access | child apps and human maintainers can use this
user info access | admins can use this for support
"ownership" concept | people can view their own profile, but not others; people may have write access for a request they created

### Documentation

> The database's structure is a little bizarre, with the users.api_key column potentially being filled by either a temporary API key, a Search Token key, or a permanent admin key.

- [ ] clarify the purpose of SECRET_KEY in the README with other env explanation
  - if this should be API_KEY, let's rename it in v2 and end this madness

**Comment by maxachis** [comment]
@joshuagraber What do you think of this as an option?

**Comment by joshuagraber** [comment]
Looks pretty solid and well-supported to me, and IMO it's almost always better to use a well-maintained library for auth, given the complexities around it.

Seems like this will handle 1. basic alias/pw auth and 2. providing access tokens to logged in users. @maxachis Do you feel confident that we can pair this with our own basic auth strategy for the public-facing endpoints?

--

Also, just bc I was thinking about it: we'll need to generate a basic API key for the client at some point. Nbd, but we'll need that before the client can start talking to the API at all.

**Comment by josh-chamberlain** [comment]
related to #296

**Comment by joshuagraber** [comment]
@josh-chamberlain Ah, yes, that changes the calculus. I didn't know we were looking into oauth. We_definitely_ don't want to build an oauth system if we don't have to. There are just at least a thousand and four ways to get it wrong, and it's something we really don't want to get wrong. @maxachis [This lib](https://github.com/lepture/authlib) seems to have Flask support for both, would that be something to look into?

**Comment by maxachis** [comment]
> @josh-chamberlain Ah, yes, that changes the calculus. I didn't know we were looking into oauth. We_definitely_ don't want to build an oauth system if we don't have to. There are just at least a thousand and four ways to get it wrong, and it's something we really don't want to get wrong. @maxachis [This lib](https://github.com/lepture/authlib) seems to have Flask support for both oauth and standard HTTP strategies, would that be something to look into?

I'm happy to look into it! This will be a ground floor sort of thing, as I've never implemented something like this before (or indeed any sort of authentication thing).

**Comment by joshuagraber** [comment]
> I'm happy to look into it! This will be a ground floor sort of thing, as I've never implemented something like this before (or indeed any sort of authentication thing).

Nice, thank you @maxachis. I've done some auth stuff in node before, so if you're wanting input on architecture or high-level conceptual stuff, lmk. I don't feel fluent enough in Python to know how to implement in a Pythonic way, though 😅.

**Comment by josh-chamberlain** [comment]
@maxachis in addition to whoever you know, PDAP has access to a loose group of experts, who can give advice with various levels of detail. If you come up with questions as you work on this, or want help with the planning, we can make it happen with a quickness.

**Comment by maxachis** [comment]
Beginning the research process. Here's some resources I've found that probably are useful so far:

* https://www.oauth.com/ - Advertises "Step-by-step instructions and real-world examples" to build OAuth.
* https://docs.authlib.org/en/latest/index.html - Documentation for Authlib.

**Comment by maxachis** [comment]
@josh-chamberlain One thing worth considering now is whether we want multiple options for Authentication, for example:
* Email and Password
* Github
* Google

These could all be associated with a single user in the database. Adds complexity but useful for those who don't have one of the authentication methods (or don't want to use a particular one with us).

**Comment by maxachis** [comment]
> @maxachis in addition to whoever you know, PDAP has access to a loose group of experts, who can give advice with various levels of detail. If you come up with questions as you work on this, or want help with the planning, we can make it happen with a quickness.

@josh-chamberlain I would want to reach out to some of these experts, as that would help me figure out how to best plan this development.

**Comment by joshuagraber** [comment]
> Also. There are rarely any one-time-only user cleanup or user migration or user audit tasks. They tend to live forever, but only get used once or twice a year. Treat them as CLI apps. Unit test. acceptance test. All the things.

This makes sense to me. When I've done migration tasks previously, it's been with utility scripts written in bash or node, and setting them up to be called manually from the command line. But...

> It’s often necessary to have a User class hierarchy with the app-specific stuff separate from the indentity and authentication stuff. Two parallel data structures lead to a bunch of fussy CLI apps to synch them manually.

...As long as each is tied to a user id, it doesn't really matter how many different classes we use for the data. i.e. The architecture _could_ have a table that stores `UserProfile`, which includes name, email, etc., and a table that stores `UserAuth`, which would contain auth-related stuff... I don't think we would need to write scripts to sync all of this stuff. Just update records as we need to. I guess we _could_ run a whole separate DB and service for auth, but I don't think that's necessary unless we're building it ourselves.

**Comment by maxachis** [comment]
# Implementation Plan

@josh-chamberlain @joshuagraber , here is my current plan for how I'm going to approach the permissions revamp, both to keep you guys in the loop on the high-level details and also so you can stop me if you think I've _**GONE TOO FAR**_:

- [ ] Replace `@api_key` with `@api_key_required`, which is used to validate that the user has an API key.
- [ ] Give all users a single API key, which can be refreshed through the `/api_key` endpoint. `users.api_key` column will default to providing an API key at user creation, if one is not provided.
- [ ] FOR TESTING PURPOSES ONLY: create special app-based API keys where the API key is pre-set (so that a random one isn't provided on each database refresh). Ensure these are eliminated upon final move to production.
- [ ] Add `permissions` and `user_permissions` table. Create an endpoint called `permissions` where an admin can `POST` and `DELETE` permissions from a user, and `GET` all permissions a user has.
- [ ] Modify `@api_key_required` so that it can accept a permissions parameter enum, and then use that to limit endpoints requiring certain permissions. 
- [ ] Remove `search_tokens` and associated logic
- [ ] Remove `access_tokens` and associated logic.
- [ ] Deprecate `/refresh-session` to be used later for JWT
- [ ] Create separate issue for creating JWT.
