### ISSUE TITLE
Replace Airtable

### ISSUE THREAD

**Issue by josh-chamberlain** [Police-Data-Accessibility-Project/data-sources-app#32]
## Context
Airtable is a great prototyping tool, and a way to show our work publicly for ~free. It's convenient for individual users to interact with. Now that we have a better interface for searching, would we select Airtable as a database management tool? Probably not. 

If, without Airtable, we want to make internal tools, we have https://retool.com/

A few more reasons to replace Airtable:

- very limited database size
- clunky API access (not suitable for modern front end)
- we want _one source of truth_ for stuff, fundamentally
- auth/login are tricky, making community interaction/ownership difficult

### Critical for v2:
- [x] API access: https://airtable.com/app473MWXVJVaD7Es/api/docs
- [x] Publicly view database without auth #83 
- [x] database admin/editing (achieved with API endpoints)
- [x] https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/256 
   - [form here](https://airtable.com/app473MWXVJVaD7Es/tblV2ftkAwaNJfDTJ/viwfnmjqzzSXYQdZh?blocks=hide), [current public view here](https://airtable.com/app473MWXVJVaD7Es/shrpwCQ0z5hOFQuOV) 
- [x] UI for editing sources one by one: https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/163
- [x] Data Source intake via form: #252 
- [x] Data Source and Requests approval, replaced by Retool workflow: #74

**Comment by DouglasKrouth** [comment]
@josh-chamberlain Does this tie into #1 ? If there's interest in migrating from Airtable to Postgres and building a service around it, I'd be happy to look into this.

Sorry to double-dip the issue response if that's the case, just looking for some clarification on this one.

**Comment by josh-chamberlain** [comment]
@DouglasKrouth yes, but that issue is a bit out of date. We do have an [API live](https://docs.pdap.io/api/introduction). Maybe it's best for you to be in touch with @mbodeantor to see where exactly would be best for you to pitch in. Lots of good work going on, lots of areas in need of help with no one active.

**Comment by maxachis** [comment]
@josh-chamberlain I have my guess as to some of the reasons, but just to make sure I'm fully in the know, what are our primary motivations for replacing Airtable? What are the disadvantages of using Airtable we're trying to rectify?

**Comment by josh-chamberlain** [comment]
@maxachis definitely, updated above

**Comment by maxachis** [comment]
@josh-chamberlain Considering we're now at the point where we've got our Retool apps set up in varying states, what's next to do on this?

**Comment by josh-chamberlain** [comment]
@maxachis well, there's the front end view for `new source`—other than that, these things can happen in the future! Before I close this issue, I'll create issues for those other back end pieces so that you don't run out of stuff to do 🙉
