### ISSUE TITLE
Create typeahead endpoint which generates a list of all of our localities, counties, and states.

### ISSUE THREAD

**Issue by maxachis** [Police-Data-Accessibility-Project/data-sources-app#345]
Must also include rate limiting and debouncing.

## TODO
- [x] Set up Search Query in Database Client and test
- [x] Set up Middleware components and test
- [x] Set up Resource and test
- [x] Set up Endpoint and test
- [x] Set up Integration Test
- [x] Create PR into Dev
- [ ] Setup Gitbook PR and link in Github PR.
- [ ] Merge PR into Dev

**Comment by maxachis** [comment]
### Tentative Database Structure

Materialized view -- materialized views are precomputed results of a query stored on disk. While views execute a query every time, materialized views exist as a pseudo-table and hence deliver results faster. They also don't update each time they're used, but should generally update automatically. Effectively, caching a response. 

In the materialized view is the following:

* **display_name**: The name which appears in the typeahead suggestion
* **type**: either "State", "County", or "Locality". May be an enum called `typeahead_type`.
* **state**: The state associated with the result. Never null.
* **county**: The county, if any, associated with the result. Null when type is "State"
* **locality**: The locality, if any, associated with the result. Null when type is "State" or "County"

### Tentative Query Structure

* Per the figma, only 4 results will be shown at a time. This should be able to be easily adjusted. 
* A LIKE statement structured like `search_term%`, i.e., search for everything that begins with that term. Unioned with...
* A LIKE statement structured like `%search_term%` i.e. search for everything that contains that term. 
* Ordered alphabetically and descending (i.e., "Aa", then "Ab", and so on).

### Tentative Middleware Logic

* Likely most subject to change as I research debouncing and rate limiting.
* In its simplest form, send the search query, return all 5 columns in the materialized view as the JSON response data.

**Comment by josh-chamberlain** [comment]
Looking good. some small corrections:

- state is null for federal agencies like the FBI or United States Aggregated.
- actually, I think that's it. performance is definitely _a_ priority for this endpoint more than others, but you're thinking about it.

**Comment by maxachis** [comment]
@josh-chamberlain A few points:

### Debouncing

By my understanding, debouncing is typically implemented on the frontend rather than the backend. Which makes sense from a performance standpoint -- otherwise, you're doing the debouncing _after_ calling the endpoint, which limits the ability to limit server load.

### Rate Limiting

Rate Limiting is a complex enough process that we may want a separate issue to handle it, as a few questions crop up:
1. Do we rate limit different endpoints differently?
2. What identifier are we rate limiting? Users? IP addresses?
3. How often do we refresh a rate limit, and does that vary depending on the endpoint?
4. Do we want to retroactively apply this to other endpoints as well?

Additionally, we'll probably need to setup a table in the database, with logic for refreshing rate limits.  

And then for typeahead suggestions, we'd want to know how strict it is, how often it refreshes, how the frontend behaves when the rate limit is reached, and so on.

**Comment by maxachis** [comment]
PR set up, although a test is currently failing because I try to Refresh the Materialized View immediately after adding some additional test data, and there are some permissions problems with that.

That also begets a larger issue in that a Materialized View does not refresh automatically, and how to refresh it regularly requires [a few considerations](https://stackoverflow.com/questions/29437650/how-can-i-ensure-that-a-materialized-view-is-always-up-to-date). May need to think about this and/or create a separate issue.

**Comment by maxachis** [comment]
Another thing to take into consideration: As I understand it, calling pre-made SQL functions may be faster than running them as python queries (which is what we're doing currently). I've not benchmarked this, however, and I'm unsure if it is something that should be investigated at this juncture. 

The general consensus I'm seeing online, however, suggests that due to the nature of how functions are stored and manipulated within a database, they tend to be faster than raw queries (and would almost certainly be faster than the in-Python query constructions which we currently do now).

For what it's worth, functions can offer other benefits in addition to performance:
1. It's much harder to do SQL injection
2. It helps separate SQL logic from Python logic. With this, we would have much less SQL code populating our backend code, migrating it instead to the database (though some of this benefit may be obviated if we transition to SQLAlchemy).

The downside is that now we'd need to set up new logic, new design, et cetera. 

Unsure if worth addressing at this juncture! But worth considering.

**Comment by josh-chamberlain** [comment]
> materialized view does not refresh automatically

responded on that issue

> SQL functions

Interesting. Could we make a SQL function, for example, that returns all approved data sources? This makes the desired behavior (almost always only show approved sources) even more of a default.

One major concern I have is version control/transparency to users and devs—when core functionality is buried in the database, and not referenced in the codebase, results can be difficult to understand.

> Rate limiting

- identifiers
  - by user ID
- by endpoint
  - login is more critical and should be tighter
- timing

**Comment by maxachis** [comment]
@josh-chamberlain :

> > SQL functions
> 
> Interesting. Could we make a SQL function, for example, that returns all approved data sources? This makes the desired behavior (almost always only show approved sources) even more of a default.

We could indeed make a SQL function (or, since this wouldn't take parameters, a procedure) that does exactly that.

> One major concern I have is version control/transparency to users and devs—when core functionality is buried in the database, and not referenced in the codebase, results can be difficult to understand.

It may be germane, then, to have our migration scripts and code building components located within Github. This is already being done to a modest degree with [dev_scripts.sql](https://github.com/Police-Data-Accessibility-Project/prod-to-dev-migration/blob/main/dev_scripts.sql), which we could eventually expand (and will likely have to, once we start migrating schema changes to prod).

On the more sophisticated side, we could even use something such as [Flyway](https://documentation.red-gate.com/flyway/getting-started-with-flyway), a database versioning tool, which could enable more advanced and structured version control. However, I have no experience with it, and it would take time to explore and see if it's suitable and can be integrated to meet our needs. Granted, that's what I did with Jenkins, and that worked out fairly well.

**Comment by josh-chamberlain** [comment]
@maxachis gotcha, thanks! I think flyway is a little much for us, as I do with many tools until we need them and my thinking changes.

**Comment by joshuagraber** [comment]
A couple of suggestions (pun intended 😅): when returning only 4 results (and also not matching on a search for space-separated <Locality> <State>), users will be stuck and unable to search for `Cleveland, OH` for instance—even though it is likely the most commonly searched "Cleveland"

<img width="836" alt="Screenshot 2024-08-07 at 9 23 59 AM" src="https://github.com/user-attachments/assets/6731c510-0aef-4bb5-9577-5cfc8bc93087">

Suggestions:
1. Maybe we could return slightly more records (max 10, maybe) and/or
2. Allow a space-separated search string to match on multiple properties <locality> and/or <county>  and/or <state> (i.e. `Cleveland Ohio`, `Cleveland, Cuyahoga`, `Cleveland Cuyahoga Ohio` etc.)

Number 2 seems like a non-trivial engineering problem to solve, so I'm voting now that we just go with number 1 and add an issue to explore number 2 later on. What do you think, @maxachis?

**Comment by maxachis** [comment]
@joshuagraber Option 1 is in dev now! Literally a two character code change 😀.

**Comment by joshuagraber** [comment]
Nice @maxachis thank you!

**Comment by josh-chamberlain** [comment]
@joshuagraber Good point about number of results and people not finding what they're after—10 is a good number, but I added this issue too: https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/389
