### ISSUE TITLE
Address Security Issues ID'd by Bandit

### ISSUE THREAD

**Issue by maxachis** [Police-Data-Accessibility-Project/data-sources-app#351]
```
>> Issue: [B201:flask_debug_true] A Flask app appears to be run with debug=True, which exposes the Werkzeug debugger and allows the execution of arbitrary code.
   Severity: High   Confidence: Medium
   CWE: CWE-94 (https://cwe.mitre.org/data/definitions/94.html)
   More Info: https://bandit.readthedocs.io/en/1.7.9/plugins/b[20](https://github.com/Police-Data-Accessibility-Project/data-sources-app-v2/actions/runs/9814739986/job/27102789332?pr=46#step:5:21)1_flask_debug_true.html
   Location: ./app.py:60:4
59	    app = create_app()
60	    app.run(debug=True, host="0.0.0.0")

--------------------------------------------------
>> Issue: [B104:hardcoded_bind_all_interfaces] Possible binding to all interfaces.
   Severity: Medium   Confidence: Medium
   CWE: CWE-605 (https://cwe.mitre.org/data/definitions/605.html)
   More Info: https://bandit.readthedocs.io/en/1.7.9/plugins/b104_hardcoded_bind_all_interfaces.html
   Location: ./app.py:60:[29](https://github.com/Police-Data-Accessibility-Project/data-sources-app-v2/actions/runs/9814739986/job/27102789332?pr=46#step:5:30)
59	    app = create_app()
60	    app.run(debug=True, host="0.0.0.0")
```

## TODO
- [x] Address "flask_debug_true"
- [x] Address "hardcoded_bind_all_interfaces"
- [x] Add Database Client to bandit check (will add more security issues, but we'll ignore these for now)
- [x] Address resultant security issues id'd by Bandit
- [x] Make PR
- [x] Merge PR!
