### ISSUE TITLE
Set up Swagger API Docs

### ISSUE THREAD

**Issue by maxachis** [Police-Data-Accessibility-Project/data-sources-app#356]
Flask_restx (which our app uses) is [swagger-compatible](https://flask-restx.readthedocs.io/en/latest/swagger.html), which automatically documents the API based on method definitions. It's pretty nifty, but we currently don't have the code properly set up to do it, or a means to migrate it into a document that can be viewed outside of the source code itself. This is an issue to work on that.

# Tasks
- [x] Correct existing code so that Swagger representation of endpoints accurately provides sufficient information to run the relevant endpoints
- [x] Determine a means to export this documentation to _the web_  so that people can view it independently of the code base.
- [x] Deprecate GitBook API docs for v2 app; we can leave the v1 stuff for now
- [x] Create Issue "#363"
- [x] Create Issue "#362"
- [x] Address bug mentioned in "Server API Bug"

**Comment by josh-chamberlain** [comment]
Currently, when I run the app locally, going to the base url shows me these docs. Could we deploy it that way, too?

**Comment by maxachis** [comment]
# Implementation Todo

- [ ] Create first draft of Swagger doc for all responses
- [ ] Figure out `security='apikey'` security setting.
- [ ] Manually test responses using Swagger API.

**Comment by maxachis** [comment]
# Implementation Notes

These add a considerable amount of code to the `resources` files. I consider this acceptable, because this information would otherwise be included in the Gitbook, but it is worth noting. I have included a set of implementation notes in a README located within the `resources` directory, to aid in deciphering some components. Once understood, it is fairly intuitive, but "once understood" is the crucial part.

**Comment by maxachis** [comment]
Bug listed in "Server API Bug" has been addressed, and the (Draft) Swagger documentation on the API is now available at https://data-sources-v2.pdap.dev/api

**Comment by josh-chamberlain** [comment]
gitbook docs deprecation complete: https://app.gitbook.com/o/-MXypK5ySzExtEzQU6se/s/-MXyolqTg_voOhFyAcr-/~/changes/510/api/v2-api-docs-wip
