### ISSUE TITLE
Refactor and consolidate testing logic

### ISSUE THREAD

**Issue by maxachis** [Police-Data-Accessibility-Project/data-sources-app#374]
While I'm very proud of all my beautiful unit and integration test children, they've got some redundant and boilerplate code which could be refactored and consolidated into less code that is more reusable. 

The gold standard for good-looking tests is `test_endpoints.py`, which tests that expected endpoints can be called with the expected HTTP methods (and that disallowed HTTP methods are not called). Adding tests to that is trivially easy. That model probably can't be emulated for most of the more complex logic I'm testing, but it is a good model to strive towards

This may be blocked by #297. Or, they could be completed concurrently.

# TODO
- [x] Apply general refactoring to satisfaction
- [x] Migrate `helper_functions.py` to `helper_scripts`
- [x] Migrate `DynamicMagicMocks` class to its own `DynamicMagicMocks.py` file in the `helper_scripts` directory.
- [x] Apply `DynamicMagicMocks` logic to tests to reduce boilerplate code.
- [x] Some middleware tests are interfacing with the database where they should not. These should be mocked. If database functionality is being tested on these that isn't currently tested in db_client tests, add these to the db_client tests.

**Comment by maxachis** [comment]
> This is fine and good, but I'd really like to consider this a blocker: #297

Noted, and description updated!

**Comment by josh-chamberlain** [comment]
Or, they could be completed concurrently!
