### ISSUE TITLE
database: agencies with multiple locations

### ISSUE THREAD

**Issue by josh-chamberlain** [Police-Data-Accessibility-Project/data-sources-app#454]
### Context

There are cases where multiple localities will share a police department. Thus, we may have localities which aren't represented in our data. Thus, if someone searches for one of those small localities which has no PD, they will not find it in the typeahead.

Let's assume that mapping the jurisdiction of police departments is our job, and allow for the complex nature of jurisdiction. 

### Requirements

- [x] agencies and localities should have a linking table
   - there may be odd cases where agencies will have jurisdiction over multiple counties, especially courts; can we use the same linking table?
- [x] POST and PUT requests will need to change to allow many-to-many agency-to-location mapping.
- [x] Inaugurate by addressing location `12955`, `Cheswick, Springdale, East Deer`, splitting it up to three locations and associating all of them with agency `17540`, `Allegheny Valley Regional Police Department`

**Comment by maxachis** [comment]
I could envisioning us updating the `POST` and `PUT` requests to a similar structure that we have with `/data-requests/{resource_id}/related-sources`, but with one caveat:
* We should still retain the option for adding/requiring an initial location when originally adding an agency (except in the case of `Federal` jurisdictions).
* We would then modify the `PUT` request so that `location_info` can't be updated through this fashion
* To update the location in this manner, you'd need to use the `/agencies/{resource_id}/related-locations` endpoint, adding and removing relations.

@joshuagraber , what do you think?

**Comment by joshuagraber** [comment]
@maxachis That generally sounds good to me. One point of clarification, though:

> We would then modify the PUT request so that location_info can't be updated through this fashion

Do you mean a `PUT` request to `/agencies/{resource_id}`? If so, can you explain why we wouldn't be able to update location info there and would require a separate endpoint? Are there performance or architectural considerations that make that difficult?

**Comment by maxachis** [comment]
@joshuagraber The main challenge is that location information is now normalized and centralized in the database. I describe the full process and logic [here](https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/450), but here's the brief for the part relevant to us:
* Previously, each component of an agency's locational information was independently specified -- you could specify the `state_iso`, `county_fips`, and `municipality`, and modify each at will.
* However, this made lookups more difficult and promoted inconsistencies -- we ran into an issue recently where [agencies were listed with counties which were not in the states they also listed](https://github.com/Police-Data-Accessibility-Project/data-projects/issues/88), for example.
* Now, when we add agencies, the locational information provided is checked for inconsistencies and cross-referenced with our locational data to ensure it's a valid location. In the case of `localities` which have a valid county and state specified but we don't have the locality in our database, we assume it's a locality we don't yet have in our database, and add it.

The issues that arise from this are:
1. It would be difficult to update an agency's locational information only partially -- if in the PUT request you modify the `state_iso` but don't mention `county_fips` or `municipality`, do we interpret that as meaning the latter fields are unchanged or that they should be `NULL`? What if you remove the municipality information and say it's location is a county? What if the `jurisdiction_type` changes from `State` to `Federal`, which would imply it's not associated with any specific state-level location? I have means of addressing this in my current endpoint design, but it's imperfect and convoluted and I don't like it.
2. If we have multiple locations, these problems remain and compound, because how do we update one of multiple locations, or potentially several at once, within the `PUT` request? 

It strikes me as easier, for both the user and the backend, to simply have it that you can add and remove locations via a separate endpoint, and leave the `PUT` request solely for non-locational information about the agency. 

I do think it makes sense to enable the inclusion of location information in the original `POST` request, since most agencies will have locational information attached to them. It just becomes quite hinky if we then enable editing through a `PUT` request.

**Comment by maxachis** [comment]
As a further note to myself, I have found one location that does appear to be three locations and should be separated. This is location id `12955`, representing the locality `Cheswick, Springdale, East Deer`. This will need to be accounted for.

**Comment by maxachis** [comment]
## Tasks

- [ ] Create `link_agencies_locations` table
- [ ] Add `link_agencies_locations` table to `change_log` tracking
- [ ] Transfer `agency.location_id` values to `link_agencies_locations`
- [ ] Update `/agencies` `GET` to return all locations included
- [ ] Modify tests for the above
- [ ] Update `/agencies` `POST` to accept an array of linked location ids, rather than a singular attribute
- [ ] Modify tests for the above
- [ ] Update `/agencies` `PUT` to remove reference to location ids
- [ ] Modify tests for the above
- [ ] Add `/agencies/{agency_id}/locations` `GET`, `POST` and `DELETE` methods which retrieve, add, and remove location links to a given agency
- [ ] Add tests for the above
- [ ] Delete `agency.location_id` column

**Comment by maxachis** [comment]
@josh-chamberlain @joshuagraber Just as a heads up, this will create **unavoidably breaking changes**. The conversion of the agency-location association from one-to-one to one-to-many necessarily means that how agencies are represented in the API must differ -- most notably, instead of locations being represented in a flat manner alongside other attributes of an agency, such as `name`, they have to be presented as a nested list.

I can dive into the client side and make adjustments. In some cases, these are fairly minor. In other cases, particularly with `GET` requests targeting agencies, you would need a different way to display agency location information. The only way that could be avoided is if it we deliberately truncated what agency location we show, and treat the first location as having primacy -- which I can do as a way to reduce the friction for the moment.

**Comment by maxachis** [comment]
> [@maxachis](https://github.com/maxachis) I appreciate the creative approach to avoiding a breaking change! We would still need to update the client if we wanted to make use of those locations instead, right?

@josh-chamberlain Precisely! This just works as a stopgap solution!
