### ISSUE TITLE
V1 to V2 Database Migration Plan

### ISSUE THREAD

**Issue by maxachis** [Police-Data-Accessibility-Project/data-sources-app#456]
### Context

* As we inch closer to the rollout of v2, it behooves us to start thinking about how the migration from the v1 to v2 database will look.  
* heavily related to #32 
* part of #248 

### Requirements

- [x] Decide on a database migration plan that answers that various open questions we have developed.

#### advance setup (can be done anytime)
- #540
- #538 
- #541
  - we don't need _frequent_ backups going back in time, but what if we had something like: frequent backups for the past 7 days; weekly for the past month; monthly for the past 6–12 months?

#### prod-to-dev
- [x] Take stock of migrations in our `prod-to-dev` repo
  - I think a manual paper trail makes sense; we have a small team and I like keeping manual processes until automation seems safe/boring/necessary
- #596
  - at this point, the database schema can just use `name`
- #597
  - we can now do this: https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/453
- #598
- #599
- this is where we would do these over-my-head steps: 
   - [x] We'll need to set up each database change to be a separate update script that we store partly for posterity and partly in case we need to do an emergency rebuild from an earlier version. And we'll need to figure out how to name and store them such that we can retrace them as needed if we want to.
   - [x] Testing migrations and updates will likely need to be more rigorous. At the moment, we can afford to be somewhat lax because the dev/stage databases are refreshed daily from production. But once our chances will more immediately impact Production, we'll need to be more strict.

#### sunset v1
- [x] destroy digitalocean v1 apps 
- [x] start using retool for intake, and the API for edits
- [x] Sunset the v1 database(s)
  - store a copy of the `dump file`
  - retain Airtable for 6 months in case we need to restore it or go back

### notes on scenarios
- it's OK if the database goes stale, or does not update for a week because something broke and we need to fix it. not ideal, but OK. we could switch back to Airtable for submissions and sort out the changes later.
- it's really bad if search totally stops working, or people can't submit things at all.

### Tests

* TODO

### Docs

- [x] we need internal Notion documentation about each database:
  - what is it for, generally?
  - which routes/domains show data from it? (v2/dev, v2/main, v1/dev, etc)
  - which routes modify data in it?
  - is it synced or refreshed periodically or manually? if so, how?

### Open questions

I believe these are resolved.

**Comment by maxachis** [comment]
# Nightmare Scenarios - A database error goes undetected and impacts a lot of data

These are scenarios where a simple rollback cannot be easily done without risking the loss of a lot of good quality data. For example:

1. Suppose a fat finger erroneously updates a large amount of data requests all at once, and we only notice this after other data requests have been added onto it, perhaps for several weeks? 
2. Suppose data becomes duplicated into multiple similar but slightly different forms, and they're all updated separately?
3. Suppose a link between an agency and a source, or an agency and a location, becomes misconfigured, and we've been returning incorrect search results for a long time?

There are three different things we'd need to think about

1. How can we **Prevent** such situations from happening?
2. How can we **Mitigate** such situations when they occur?
3. How can we **Recover** from these situations once they're detected?

**Comment by maxachis** [comment]
# Quickly Identified and Resolved Backups

* We want to test backups on a regular basis to make sure they actually work with restoring data -- data integrity tests on our regular database should also work on the new database.
* We want to have a plan in place, with instructions, for how to perform a backup if it needs to occur.
* We need to examine our backup storage plan -- how long are our backups stored (and do we want to change that? Are these backups incremental (i.e., they only repeat a lot of transactions but don't store the data) or full (they restore the data from a specific space)?

**Comment by maxachis** [comment]
# What do we do with the current production database?

My thinking is we want to store a permanent copy of the old production database and be able to restore it to a temporary database where necessary. As the v2 database matures, this becomes less necessary, but in the case of errors we want to be able to retrace our steps from the original format.

**Comment by maxachis** [comment]
# What about the current prod-to-dev migration logic?

This will likely need to change. Our current setup runs on the assumption that we'll do a lot of data transformations all at once, once we finally transition from v1 to v2. In the future, We'll need to design for situations where the production database will be updated more frequently, and where we can retrace migrations if and when they occur.

**Comment by maxachis** [comment]
# What do we do with limited resources?

* Ouncing off prevention pounds the cure. A well-designed database with proper constraints will stop most errors before they occur. 
* As far as nightmare scenario prevention goes, we should ID the most probable and severe scenarios and attend to those, and lower priority for less likely ones. So that involves identifying which scenarios _are_ most probable and severe.
* Not everything needs to be kosher prior to v2 launch. We can add stuff as we go along.

**Comment by maxachis** [comment]
# How will we set up the new production database?

We're already partway there! We've got a V2 Production database set up in digital ocean, and a manually triggered script which refreshes from prod v1 to prod v2. Once we're ready to make the switch, we'll sunset ProdV1 and disable/remove the manual refresh.

**Comment by maxachis** [comment]
#  How do we maintain a paper trail of migrations and updates?

The simplest thing we could do is create a directory in our prod-to-dev migration repository (which will probably need to be renamed) that can contain datestamped records of all files. With this, the onus is on us to make sure we document everything properly and clearly so that things can be quickly rebuilt if necessary.

We could use something more elaborate such as [Flyway](https://www.red-gate.com/), but that becomes a new set of tools to learn, and it's possible the free trial version (I doubt we want to pay $600 per year per user) may not have the features we need. But it's worth investigating.

**Comment by josh-chamberlain** [comment]
Here's my attempt at a summary of the above in task list form, in order. Does this make sense? What is missing?

#### advance setup (can be done anytime)
- [ ] start using v2 search/results (I think the db is stable enough for that)
- [ ] set up database health monitoring
- [ ] make backup storage more robust
  - we don't need _frequent_ backups going back in time, but what if we had something like: frequent backups for the past 7 days; weekly for the past month; monthly for the past 6–12 months?

#### prod-to-dev
- [ ] Take stock of migrations in our `prod-to-dev` repo
  - I think a manual paper trail makes sense; we have a small team and I like keeping manual processes until automation seems safe/boring/necessary
- [ ] modify stage/sandbox to refresh from v2 instead
- [ ] eliminate [dev_scripts.sql](https://github.com/Police-Data-Accessibility-Project/prod-to-dev-migration/blob/main/dev_scripts.sql) in the migration repo, and modify the migration scripts accordingly.
- [ ] this is where we would do these over-my-head steps: 
   - We'll need to set up each database change to be a separate update script that we store partly for posterity and partly in case we need to do an emergency rebuild from an earlier version. And we'll need to figure out how to name and store them such that we can retrace them as needed if we want to.
   - Testing migrations and updates will likely need to be more rigorous. At the moment, we can afford to be somewhat lax because the dev/stage databases are refreshed daily from production. But once our chances will more immediately impact Production, we'll need to be more strict.

#### sunset v1
- [ ] replace links to Airtable submission forms with v2
- [ ] Sunset the v1 database(s)
  - store a copy of the `dump file`
  - retain Airtable in case we need to restore it or go back

**Comment by maxachis** [comment]
> Here's my attempt at a summary of the above in task list form, in order. Does this make sense? What is missing?

@josh-chamberlain At a glance, this seems right, but we can refine it as we go along. I think the next step is to move this into the heading of this issue and make it an `epic` or create a new `epic` issue. Then we will begin creating the sub-issues as needed!

**Comment by josh-chamberlain** [comment]
@maxachis OK, done!
