### ISSUE TITLE
Add pagination and result limiting for `/archives` `GET`

### ISSUE THREAD

**Issue by maxachis** [Police-Data-Accessibility-Project/data-sources-app#545]
### Context

* Currently, `/archives` `GET` has no means to paginate or limit the number of results obtained.
* As the amount of archived data sources increases, this will pose a problem

### Requirements

* Update `/archives` `GET` to include a page parameter (defaulting to 1)
* Update `/archives` `GET` to limit the number of results per page to 100 (same as with other `GET-MANY` endpoints)
* Refactor internal logic of `/archives` to bring in line with other endpoints
* Update `/archives` `GET` tests to test the above two additoins.

### Tests

* Tests should be updated as per above

### Docs

* Documentation will need update

### Open questions

* None at this time.

**Comment by maxachis** [comment]
## Tasks

- [ ] Add pagination and limiting
- [ ] Add `archive_frequency` and `last_archived_before` query parameters, which will be used to filter the `GET` requests
  - [ ] `archive_frequency` pulls entries which match that specific archive frequency
  - [ ] `last_arrchived_before` pulls entries which were last archived before the given date.
- [ ] Update Archiver to pull based on these filters (as opposed to what it is doing now where it is pulling everything and then sorting through the results.
