### ISSUE TITLE
october 2023 schema update

### ISSUE THREAD

**Issue by josh-chamberlain** [Police-Data-Accessibility-Project/data-sources-app#62]
### Context

These properties are unused, barely used, or questionably useful. Removing them will make everything else just a bit easier, because there can be fewer properties.

#### Child issues below:

1. Have PRs ready to merge in /data-sources-app and /data-sources-mirror to ensure that these fields being absent in Airtable will not break anything else, and ready to add the new fields to the database + API endpoints

2. Have a PR ready to merge in docs removing these from the data dictionary, and adding the new fields

#### This issue: 

3. Make changes in Airtable

### Requirements

- [x]  simplify `update_method` options to `Overwrite`, `Insert`, `No updates`
- [x]  remove `sort_method`
- [x]  remove `private_access_instructions`
- [x]  remove `access_restrictions`
- [x]  change `access_restrictions_notes` → `access_notes`
- [x]  remove `community_data_source`
- [x]  remove `record_download_option_provided`
    - [x]  replace with “Download” in `access_type` options
- [x]  create `url_status` (single select)
    - [x]  remove `records_not_online` → `url_status` `none found`
    - [x]  remove `url_broken` → `url_status` `broken`
    - [x]  add status `ok` 

### Tests

Does the mirror code still send things to supabase in a way that works? Are we getting the new properties back from the API?

### Docs

Listed above

**Comment by josh-chamberlain** [comment]
@mbodeantor synchronization isn't a huge deal with this one, but I figure someone else should submit a PR or two against this (if needed), at which point I'll do my thing in Airtable and merge the PRs. This is not urgent, but the sooner we make these changes, the sooner the schema is that much smaller & simpler

**Comment by mbodeantor** [comment]
Created child tickets:
Docs: https://github.com/orgs/Police-Data-Accessibility-Project/projects/21/views/1?pane=issue&itemId=40198475
Mirror: https://github.com/orgs/Police-Data-Accessibility-Project/projects/21/views/1?pane=issue&itemId=40199312
API: https://github.com/orgs/Police-Data-Accessibility-Project/projects/21/views/1?pane=issue&itemId=40200102
Supabase edits: https://github.com/orgs/Police-Data-Accessibility-Project/projects/21/views/1?pane=issue&itemId=40200470

**Comment by mbodeantor** [comment]
@josh-chamberlain was it meant to be "add records_not_online"? Not seeing that one

And is that "status" column just default to "ok" unless there is a reason to mark it otherwise?

**Comment by josh-chamberlain** [comment]
@mbodeantor that one's in Airtable, if it's not in Supabase that's ok. Defaulting to OK is fine, sure! Down the road we can get more sophisticated and show the http response codes and stuff

**Comment by josh-chamberlain** [comment]
done in airtable

**Comment by josh-chamberlain** [comment]
@mbodeantor is it too late to also address `broken_source_url_as_of` ? I'm thinking it could just be `url_status_updated`. I didn't know about that one, I would also add it to the data dictionary 👀
