### ISSUE TITLE
2023 app launch

### ISSUE THREAD

**Issue by josh-chamberlain** [Police-Data-Accessibility-Project/data-sources-app#83]
### Context

Goal for this issue: 
~11/17/23~ lots of progress, but we keep adding stuff to the list!
~12/8/23~ tons of progress! done by EOY for sure
~12/15/23~ everything's working—just needs aesthetic tweaks
12/20/23 for everything to be deployed

### Requirements

- [x] = work complete; issues being closed means things are merged into `main`

#### Site
- [x] https://github.com/Police-Data-Accessibility-Project/pdap.io/issues/133
- [x] https://github.com/Police-Data-Accessibility-Project/pdap.io/issues/146

#### App

- [x] #85
- [x] https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/130
- [x] updated nav items (after using design system components)
- [x] updated copy, more in line with issue 133 linked above
- [x] add a link to airtable public view saying something like "View all data sources" and a table icon
- [x] label/value differentiation
- [x] cramped search results
- [x] clarify that "visit source URL" will take users to a new page ([icon](https://fontawesome.com/v4/icon/external-link))
- [x] mobile testing
   - [x] quick search
   - [x] results
- [x] https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/92
- [x] https://github.com/Police-Data-Accessibility-Project/data-sources-app/pull/86
- [x] https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/81
- [x] https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/80
- [x] https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/82
- [x] https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/76
- [x] https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/93

#### Airtable
- [x] refine "make a request" form
- [x] create anonymous grid view of requests

#### Docs
   - [PR here](https://app.gitbook.com/o/-MXypK5ySzExtEzQU6se/s/-MXyolqTg_voOhFyAcr-/~/changes/446/)
- [x] wildly simplify; particularly related to exploring data sources
- [x] make updated docs about tips & pitfalls of using quick search
